export const colors = {
  backgroundWhite: "#FFFFFF",
  warmWhite: "#FFF8F5",
  softSurfaceTint: "#FFF3EC",
  primaryOrange: "#F97316",
  primaryGradientStart: "#FB923C",
  primaryGradientEnd: "#F97316",
  orangeSoftSurface: "#FFF1E8",
  orangeBorder: "#FED7AA",
  softOrange: "#FB923C",
  peachGlow: "#FDE7DC",
  softTeal: "#5BBFB5",
  tealSoftSurface: "#E8F7F5",
  paleCoral: "#FF8A7A",
  secondaryCoral: "#FF8A7A",
  coralSoftSurface: "#FFE8E3",
  softPink: "#F9A8D4",
  pinkSoftSurface: "#FCE7F3",
  roseGold: "#C98F7A",
  lavenderMist: "#EDE7F6",
  primaryText: "#2D2A26",
  secondaryText: "#6B665F",
  mutedText: "#9B928A",
  whiteText: "#FFFFFF",
  softDisabled: "#E8E2DC",
  disabledText: "#A49B92",
  divider: "#F1E6DD",
  dividerText: "#9B928A",
  successText: "#2F7D55",
  successSurface: "#EAF7EF",
  warningText: "#9A5B00",
  warningSurface: "#FFF4D8",
  dangerText: "#B94A48",
  dangerSurface: "#FDECEC",
  dangerSoft: "#FDECEC",
  cardBorder: "#F1E6DD",
  orangeShadow: "rgba(249, 115, 22, 0.45)",
  coralShadow: "rgba(255, 138, 122, 0.42)",
  softOverlay: "rgba(255, 248, 245, 0.96)",
  tourOverlay: "rgba(45, 42, 38, 0.36)",
} as const;

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 40,
  xxxl: 48,
  huge: 56,
  giant: 64,
} as const;

export const radius = {
  button: 8,
  input: 8,
  small: 16,
  medium: 20,
  large: 24,
  full: 999,
} as const;

export const shadows = {
  xs: {
    shadowColor: colors.coralShadow,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  sm: {
    shadowColor: colors.coralShadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  md: {
    shadowColor: colors.orangeShadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  lg: {
    shadowColor: colors.orangeShadow,
    shadowOpacity: 0.1,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 9,
  },
  card: {
    shadowColor: colors.coralShadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  button: {
    shadowColor: colors.orangeShadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  fab: {
    shadowColor: colors.orangeShadow,
    shadowOpacity: 0.1,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 9,
  },
  tabBar: {
    shadowColor: colors.coralShadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
} as const;
